@baseUrl = http://localhost:8000/api/v1


POST {{baseUrl}}/products/
Content-Type: application/json
{
  "title": "p1",
  "description": "product 1"
}


GET {{baseUrl}}/products/
Content-Type: application/json


PATCH {{baseUrl}}/products/1/
Content-Type: application/json
{
  "description": "product 1.2"
}


DELETE {{baseUrl}}/products/1/
Content-Type: application/json


GET {{baseUrl}}/products/?search=2
Content-Type: application/json


POST {{baseUrl}}/stocks/
Content-Type: application/json
{
  "address": "address 1",
  "positions": [
    {
      "product": 1,
      "quantity": 10,
      "price": 100.25
    },
    {
      "product": 2,
      "quantity": 20,
      "price": 150
    }
  ]
}


PATCH {{baseUrl}}/stocks/1/
Content-Type: application/json
{
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 250,
      "price": 150
    }
  ]
}


GET {{baseUrl}}/stocks/?products=3
Content-Type: application/json
